### ISSUE TITLE
Cleanly exit threads if streaming is complete

### ISSUE THREAD

**Issue by phunkyfish** [e2iplayer/hlsdl#11]
Hi,

I'm using this as a library in some C++ code for live streaming.

If the user if finished streaming it would be great to be able to cleanly exit threads so the application finishes. Maybe by settings some thread aware variable in main.

Thoughts?

**Comment by e2iplayer** [comment]
Hello,

I am not sure what you mean by
>   cleanly exit threads

Before return from function **download_live_hls**  there is pthread_join called.
So, this i clean exit.  Both, download_live_hls end hls_playlist_update_thread exit when **is_endlist**

Or maybe you want to have possibility to cleanly break download?

**Comment by phunkyfish** [comment]
That’s what I was looking for. 

However I’ve ported enough of the code across to C++ to be able to handle the this myself. Wasn’t sure I would get it to work and just got it working this morning 😉

**Comment by phunkyfish** [comment]
So I’ll close the issue.
