### ISSUE TITLE
Mechanism to stream to an output stream 

### ISSUE THREAD

**Issue by phunkyfish** [e2iplayer/hlsdl#12]
Currently the application saves everything to a file. Would it be possible to have the option to stream to some sort of output stream instead of a file if one chooses.

The output stream could be directed to a file if one chooses.

**Comment by e2iplayer** [comment]
Hello,

I can add interface with callback which will be called with buffer and it size to be written/copied.
At now also stdout can be used to output video/audio data, so not only the file.

**Comment by phunkyfish** [comment]
That would be cool

**Comment by phunkyfish** [comment]
As I stated in the other issue I’ve managed to port enough of the code to be able to manage most of the IO.

The last thing I need to do is get the data from mpegts out to a data buffer to get this work fully.

**Comment by phunkyfish** [comment]
Not quite sure how to handle this.

**Comment by e2iplayer** [comment]
I will add this today or tomorrow.

**Comment by phunkyfish** [comment]
Is the max size of the output buffer required for a call to merge packets determinable?

If so a buffer could be added to the merge context to store the resulting output.

Thoughts? This way I wouldn’t have to deal with callbacks from c to c++.

**Comment by e2iplayer** [comment]
Callback is not the problem at all. Please check this example how to use from C++

```
class CTest {
public:
    static size_t static_write(const void *ptr, size_t size, size_t n, void *opaque) {
        CTest *obj = reinterpret_cast<CTest *>(opaque);
        return obj->write(ptr, size, n);
    }
private:
    size_t write(const void *ptr, size_t size, size_t n) {
        // do with the buffer whatever you want 
        const uint8_t *buffer = reinterpret_cast<const uint8_t *>(ptr); 
        return 0;
    }
};
...
            CTest *pTest = new CTest;
            write_ctx_t out_ctx = {CTest::static_write, reinterpret_cast<void *>(pTest)};
            ret = download_hls(&out_ctx, &media_playlist, &audio_media_playlist);
...
```

**Comment by phunkyfish** [comment]
Thanks, makes sense. However I think I still have the same problem. 

I would require the callback to come to the calling objects function and not a static one. The data is still in limbo, it’s moved from C to a static in c++ but still not accessible by another object.

From here I would need to save to a file or make a network call to read/write the data. But I already use a file right now so it doesn’t really gain me anything. Another option would be a static buffer for the data but it’s just not very clean and I could never have more than one stream at a time.

**Comment by phunkyfish** [comment]
Or does this work internally from an object using ‘this’?

**Comment by e2iplayer** [comment]
Hello,

Do you have any further questions?
If not please close this issue.

Regards,
SSS

**Comment by phunkyfish** [comment]
Was the output callback added?

**Comment by e2iplayer** [comment]
Yes, it was added. I wrote you example how to use it after adding

https://github.com/e2iplayer/hlsdl/commit/be2e70cb9c31760c9e8dab6e58426a5ed3d25eac

**Comment by phunkyfish** [comment]
Sorry, was keeping an eye in the commits. I missed it there 😉

**Comment by e2iplayer** [comment]
Yes. It is interface of function fwrite(...)
and theoretically it can be also  uint32_t * , this is why you have size and count params

**Comment by e2iplayer** [comment]
Because it was used before your request. 
It is any problem?

**Comment by phunkyfish** [comment]
No, not at all.

I just changed misc.h and the other references to the function so it matches my c++ signature and it appeared to work so just wanted to check.

I have the changes made here. I’ll create a PR ;)
