### ISSUE TITLE
Question - englandproxy

### ISSUE THREAD

**Issue by phunkyfish** [e2iplayer/hlsdl#13]
I started to port some of the c code to c++. I'm a bit confused by the code below. I'm not sure the condition ```if (strstr(baseurl, proxy_marker) && !strstr(*url, proxy_marker))``` ever get's entered. Could you explain?

https://github.com/e2iplayer/hlsdl/blob/d5d755877d9d32b3f1500d6f62f2ec8101cbbfa8/src/hls.c#L188-L204

**Comment by e2iplayer** [comment]
> I'm not sure the condition if (strstr(baseurl, proxy_marker) && !strstr(*url, proxy_marker)) ever get's entered.

As comment state this is ugly  workaround for geo-location to access BBC streams via web proxy gateway:
http://www.englandproxy.co.uk/

This condition can be meet, for example:

Input:
url = "http://xxx.yy/zzzz.ts";
baseurl = "http://www.englandproxy.co.uk/xxx.yy/zzzz.m3u8"

Output:
url = http://www.englandproxy.co.uk/xxx.yy/zzzz.ts

**Comment by e2iplayer** [comment]
Do you have any further question?
If not then please close this issue.

**Comment by phunkyfish** [comment]
That’s it, thanks!
