### ISSUE TITLE
Error getting key-file (Waipu TV)

### ISSUE THREAD

**Issue by sunsettrack4** [e2iplayer/hlsdl#16]
I get an error while downloading SAMPLE-AES encrypted streams (Waipu TV).

Error: Getting key-file [https://e-f1-007-v4.wpstr.tv/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwdXAiLCJleHAiOjE1NDkyMjcxNTcsImlhdCI6MTU0OTIwOTE1NywidWgiOiI5YzFhZmIzYWY3NjBhNTYxODgwZjBmYjZhMzIyMzQ2NyIsImlwIjoiMTA5LjQxLjY2LjI0OCIsImFzIjoiWElURVNEIiwidGlkIjoiOWVhZTU4ZWQtMDE1Yi00YzljLWNjNWItYzc0ZDFmZTE5Y2U2IiwibWIiOiIxODAwMDAwIn0.iIDiv83FNys4mGNbdidYoeH197HXAACzV2z2LEh9QUo/xitesd-audio_1=128000-video=600000.m3u8/../skd://drmtoday?assetId=exrfp5c514f109794] failed http_code[404].

The file is saved to the expected path successfully but it's a scrambled video without audio.
It seems that the application is unable to retrieve the correct license server because the app outputs a HTTP 404 message.

M3U8 file attached.
[HLS-Stream.m3u8.txt](https://github.com/e2iplayer/hlsdl/files/2825817/HLS-Stream.m3u8.txt)

**Comment by e2iplayer** [comment]
This stream is protected with DRM. 
The DRM is not handled by this utlitily. 

There were already such issues.
The only think I can fix is inform that DRM protected streams are not supported.

**Comment by anddilolz** [comment]
> This stream is protected with DRM.
> The DRM is not handled by this utlitily.
> 
> There were already such issues.
> The only think I can fix is inform that DRM protected streams are not supported.

"It supports decryption of both AES-128 and SAMPLE-AES encryption." It literally says this in the description. How can it not handle DRM if it is able to decrypt SAMPLE-AES? Or do I need to supply the decryption key myself?

**Comment by anddilolz** [comment]
> > How can it not handle DRM if it is able to decrypt SAMPLE-AES?
> 
> What? Why you think then SAMPLE-AES == DRM protection. No, it does not.
> Streams could use SAMPLE-AES encryption with plain key delivery.

I see. Thank you for the reply. I did not know some providers use SAMPLE-AES with plain key delivery. I have a m3u8 playlist which asks DRM server for a key.. Then this solution will not work for me. Thanks anyway :)
