### ISSUE TITLE
Cookies

### ISSUE THREAD

**Issue by sstativa** [e2iplayer/hlsdl#19]
This is not the issue, just some thoughts.

I have URL that requires an "authentication" cookie, **hlsdl** works great at the beginning but then fails, because after a minute or two the server changes the cookie and the next request to .m3u8 fails because authentication fails.

I wonder, is it hard to track the cookie with the response and update it accordingly?

**Comment by e2iplayer** [comment]
Hello,

The problem is probably in with the libcurl. Libcurl tracks COOKIE provided by the server but it is probably always overwritten by this one provided by the option.  I will try to make futher investigation this problem maybe at the weekend.

Regards,
SSS

**Comment by sstativa** [comment]
That will be wonderful.

I was thinking about doing this myself but I don't know C.
I think I'll spend a lot of time trying to make simple things that you are able to complete in a minute.
But the thing that worries me the most is memory leaks, I'm sure I'll mess up somewhere, and this stops me.

**Comment by e2iplayer** [comment]
Hello,

In the version 0.25 I added possibility to use cookie file with Netscape format.
When you provide path to a Netscape cookie file, then also cookies set or updated by the server will be handled.

So, you should not set cookies using -h (header options), but using option -C.
For example, you want to set cookies 
```
NAME1=Value1;
NAME2=Value2;
```
And you hls url is http://www.hostname.com/playlist.m3u8

Then:
```
echo -e "hostname.com\tTRUE\t/\tFALSE\t0\tNAME1\tValue1" > /tmp/hlsdl_cookie.txt
echo -e "hostname.com\tTRUE\t/\tFALSE\t0\tNAME2\tValue2" >> /tmp/hlsdl_cookie.txt
```

and then:
```
hlsdl -C /tmp/hlsdl_cookie.txt -u "Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:21.0) Gecko/20100101 Firefox/21.0"  "http://www.hostname.com/playlist.m3u8" 
```

**Comment by e2iplayer** [comment]
No answer > close.
