### ISSUE TITLE
Codec

### ISSUE THREAD

**Issue by An0nima** [e2iplayer/hlsdl#21]
Please allow other codecs.

**Comment by e2iplayer** [comment]
Please provide more information or this issue will be closed.

**Comment by An0nima** [comment]
I mean allow in other formats such as mp4 and mkv the codec aac and avc1 and not always the codec adts, etc...

**Comment by e2iplayer** [comment]
Dead you read **ToDo** ?

If yes why you create issue?

**Comment by An0nima** [comment]
I don't speak English.

**Comment by e2iplayer** [comment]
This is on ToDo list. I do not know if and when I will find time to implement this.
There is no schedule.
