### ISSUE TITLE
How to stream directly ?

### ISSUE THREAD

**Issue by superuser789** [e2iplayer/hlsdl#22]
Hi,
hlsdl works great for downloading hls urls. But everytime I have to download first & then play .ts file using media player. This continuously writes the ts file to the storage as long as I play it using player.

How can I stream directly without downloading or writing to the storage ?  I want to use it on my raspberry pi.
Thank you.

**Comment by e2iplayer** [comment]
Hello,

You need use "-" as output file and pie it with player.

For example,
```
hlsdl http://example.com/playlist.m3u8 -o - | vlc -vvv -
```

**Comment by superuser789** [comment]
> Hello,
> 
> You need to use "-" as output file and pipe it to player.
> 
> For example,
> 
> ```
> hlsdl http://example.com/playlist.m3u8 -o - | vlc -vvv -
> ```
> Regards,

Thank you. This is working well with vlc but not at all with omxplayer.  I have come to know that omxplayer does not support stdin but works with named pipes.
Could you guide me on how to make it work with omxplayer in raspberry pi ?

**Comment by e2iplayer** [comment]
I do not know what input omxplayer accept and if it is able to accept any stream data.

> but works with named pipes.
> Could you guide me on how to make it work with omxplayer in raspberry pi ?

I do not think that this is valid question for me. If you know what exactly is needed by omxplayer then wrote here and then I can add it to hlsdl. 

You wrote about named pipes but are you sure that omxplayer are able to handle named pipes? Did you test this?

**Comment by superuser789** [comment]
> I do not know what input omxplayer accept and if it is able to accept any stream data.
> I do not think that this is valid question for me. If you know what exactly is needed by omxplayer then wrote here and then I can add it to hlsdl.

It has been discussed here [https://www.raspberrypi.org/forums/viewtopic.php?t=28017](here).

> You wrote about named pipes but are you sure that omxplayer are able to handle named pipes? Did you test this?

Yes this command using named pipe works for me 
```
./hlsdl "http://someurl/live/channel1.m3u8" -o - | tee livepipe > /dev/null 
omxplayer livepipe
```
But omxplayer stops after 50-60 seconds everytime. What could be done to avoid this ?

Thanks.

**Comment by e2iplayer** [comment]
You are asking me about omxplayer, but I am not the author of the omxplayer.

**Comment by e2iplayer** [comment]
Nothing to fix.
