### ISSUE TITLE
Please provide support for named pipes.

### ISSUE THREAD

**Issue by WuvorWenda** [e2iplayer/hlsdl#23]
If i start hlsdl (linux) to a named pipe, i get the message override the file.
Answer yes and the named pipe is gone, overwritten with the -o (file).  
The workaround is now "-o- | cat > (named pipe)"
------------------------------------------------------------------
Another question is: can you also provide a x64 windows version?
Thank you very much.

Kind regards,
Wuvorwenda.

**Comment by e2iplayer** [comment]
Hello,

Here you can find info how to compile it using  Visual Studio
https://github.com/e2iplayer/hlsdl/blob/master/msvc/BUID_WINDOWS.txt

**Comment by WuvorWenda** [comment]
That is working great -o- > named pipe.
Thank you.
I do not have VS, i work with mingw 64, are there compile instructions for mingw 64?

**Comment by WuvorWenda** [comment]
Ok thanks.

**Comment by WuvorWenda** [comment]
@e2iplayer 
VC 2017 X64 build is oke.
