### ISSUE TITLE
failed getting key file

### ISSUE THREAD

**Issue by campones** [e2iplayer/hlsdl#3]
Hi there, trying your binary but it doesn't seem to be able to decode the url

`hlsdl.exe https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8
1: Bandwidth: 118000, Resolution: unknown, Codecs: mp4a.40.2
2: Bandwidth: 4083000, Resolution: 1280x720, Codecs: mp4a.40.2,avc1.64001F
3: Bandwidth: 2567000, Resolution: 960x540, Codecs: mp4a.40.2,avc1.4D401F
4: Bandwidth: 1867000, Resolution: 960x540, Codecs: mp4a.40.2,avc1.4D401F
5: Bandwidth: 1401000, Resolution: 640x360, Codecs: mp4a.40.2,avc1.4D401E
6: Bandwidth: 340000, Resolution: 416x234, Codecs: mp4a.40.2,avc1.4D401E
7: Bandwidth: 993000, Resolution: 480x270, Codecs: mp4a.40.2,avc1.4D401E
Which Quality should be downloaded? 2
1: Name: qad, Language: qad
2: Name: vo, Language: qaa
3: Name: vf, Language: fra
Which Language should be downloaded? 3
> START media_playlist_get_links
> END media_playlist_get_links
> START media_playlist_get_links
> END media_playlist_get_links
HLS Stream is SAMPLE-AES encrypted.
{"d_t":"live"}
Downloading part 20236408
Error: Getting key-file [https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8/../skd://live/RLVTV_L2R] failed http_code[400].
{"t_d":120,"d_d":6,"d_s":2606056}
Downloading part 20236409
Error: Getting key-file [https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8/../skd://live/RLVTV_L2R] failed http_code[400].
{"t_d":120,"d_d":12,"d_s":5716516}
Downloading part 20236410
Error: Getting key-file [https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8/../skd://live/RLVTV_L2R] failed http_code[400].
Downloading part 20236411
Error: Getting key-file [https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8/../skd://live/RLVTV_L2R] failed http_code[400].
{"t_d":120,"d_d":24,"d_s":10220996}
Downloading part 20236412
Error: Getting key-file [https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8/../skd://live/RLVTV_L2R] failed http_code[400].
{"t_d":120,"d_d":30,"d_s":12871420}
Downloading part 20236413
Error: Getting key-file [https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8/../skd://live/RLVTV_L2R] failed http_code[400].
Downloading part 20236414
Error: Getting key-file [https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8/../skd://live/RLVTV_L2R] failed http_code[400].
{"t_d":120,"d_d":42,"d_s":18286384}
Downloading part 20236415
Error: Getting key-file [https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8/../skd://live/RLVTV_L2R] failed http_code[400].
Downloading part 20236416
> START DOWNLOAD LIST url[https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8]
> END DOWNLOAD LIST
> START media_playlist_get_links
> END media_playlist_get_links
Error: Getting key-file [https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8/../skd://live/RLVTV_L2R] failed http_code[400].
{"t_d":126,"d_d":54,"d_s":24134876}
Downloading part 20236417
Error: Getting key-file [https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8/../skd://live/RLVTV_L2R] failed http_code[400].
Downloading part 20236418
Error: Getting key-file [https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8/../skd://live/RLVTV_L2R] failed http_code[400].
{"t_d":126,"d_d":66,"d_s":28187592}
Downloading part 20236419
Error: Getting key-file [https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8/../skd://live/RLVTV_L2R] failed http_code[400].
{"t_d":126,"d_d":72,"d_s":31623856}
Downloading part 20236420
Error: Getting key-file [https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8/../skd://live/RLVTV_L2R] failed http_code[400].
Downloading part 20236421
Error: Getting key-file [https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8/../skd://live/RLVTV_L2R] failed http_code[400].
{"t_d":126,"d_d":84,"d_s":34716080}
Downloading part 20236422
Error: Getting key-file [https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8/../skd://live/RLVTV_L2R] failed http_code[400].
Downloading part 20236423
Error: Getting key-file [https://hls-m002.live-lv3.canalplus-cdn.net/live/disk/c8-hd/ios-hd/index.m3u8/../c8-hd-video=3400000.m3u8/../skd://live/RLVTV_L2R] failed http_code[400].
{"t_d":126,"d_d":96,"d_s":39794900}`

**Comment by e2iplayer** [comment]
Hello,

As you can see or not this stream use DRM protection:
`URI="skd://live/RLVTV_L2R",KEYFORMAT="com.apple.streamingkeydelivery"`

The DRM protection is not supported. It should be obvious. 
If there will be simple workaround for DRM protection then such protection will could not be called DRM.

Regards,
SSS

**Comment by campones** [comment]
sorry I thought it supported sample aes decryption, my bad

**Comment by e2iplayer** [comment]
It support SAMPLE-AES. I think you still do not understand.
