### ISSUE TITLE
Error when trying to download m3u8 encrypted with AES 128

### ISSUE THREAD

**Issue by dexter101010** [e2iplayer/hlsdl#6]
I am getting the following error when i am trying to download an m3u8 stream protected with AES 128 key : 

Downloading part 0
Error: AES128_CBC_DecryptUpdate failed: 0, in_size: 34032, out_size: 34016
{"t_d":1184,"d_d":2,"d_s":34016}
Downloading part 1
Error: AES128_CBC_DecryptUpdate failed: 0, in_size: 33472, out_size: 33456
Downloading part 2
Error: AES128_CBC_DecryptUpdate failed: 0, in_size: 16736, out_size: 16720
Downloading part 3
Error: AES128_CBC_DecryptUpdate failed: 0, in_size: 33664, out_size: 33648

Thanks!

**Comment by dexter101010** [comment]
Yup, the downloaded file not play. 

What is saw is that it can decrypt the aes key but each time when i do this command : 

hlsdl.exe -d https://cdn.spayee.in/spees/w/o/5b49b8f2e4b02ac9d5e71945/v/5bc57c56e4b0253afa0cb950/u/5c28ab6fe4b0efa6ebda1830/t/0c229aa71352374ab600b95cc5d2d8bc/p/assets/videos/2018/10/16/5bc57c56e4b0253afa0cb950/hls_350k_.m3u8


The key value get changed. Only the first part .  In m3u8 file you can find that value with this:

URI="k/timestamp"

Maybe this why the values get changed each time when i am extracting.

[AES-128]KEY: 0xdc1927c1382af00d3f34493cf5bd8a08 IV: 0x496daa1c6914000e408c65cead91fc29

This values are for all the segment files. After i try again the command : 
hlsdl.exe -d "https://blabla.m3u8" ,  the first value(k/timestamp) get changed.

> START media_playlist_get_links
> END media_playlist_get_links
HLS Stream is AES-128 encrypted.
[AES-128]KEY: 0xebf489a3d4163b8ea5ec888a19d413f0 IV: 0x496daa1c6914000e408c65cead91fc29

**Comment by e2iplayer** [comment]
Are you able to play this stream anywhere else?

**Comment by dexter101010** [comment]
Yes, i can play the video from where i got that link. I have a subscription to that site.


Thanks!

**Comment by e2iplayer** [comment]
So, maybe link require authentication COOKIE header or something like that or special (not standard) handling of the AES keys.

**Comment by dexter101010** [comment]
I have cookie and credentials but i don't know how to pass them to hlsdl.exe

**Comment by e2iplayer** [comment]
HTTP header also COOKIE one could be set using option:
-h ... Set custom HTTP header.

You should debug first how playback is handled by the browser to check how request for keys looks and so on. This can be done for example using "developer tools" from Google Chrome.

**Comment by dexter101010** [comment]
Thanks for your replay. I am using http debugger pro which is best option. I saw that until the course start, the browser access a link with "timestamp" in the end. I am curious why the aes key change everytime i request the m3u8 link.

**Comment by dexter101010** [comment]
> HTTP header also COOKIE one could be set using option:
> -h ... Set custom HTTP header.
> 
> You should debug first how playback is handled by the browser to check how request for keys looks and so on. This can be done for example using "developer tools" from Google Chrome.

If you need, i can give you a saved session with fidller or http debugger.

Thanks!

**Comment by e2iplayer** [comment]
Need? What for?

**Comment by e2iplayer** [comment]
COOKIE as you know or not is send via HTTP header using option -h like that:
-h "Cookie: NAME_1=VALUE_1; NAME_2=VALUE_2; NAME_3=VALUE_3;"

> credentials
?

As I wrote you should debug what information are send to server when m3u8 is requested in regular player.

Sam, you should check what server return when regular player request AES key. 
In your example AES key are downloaded using URL:
https://cdn.spayee.in/spees/w/o/5b49b8f2e4b02ac9d5e71945/v/5bc57c56e4b0253afa0cb950/u/5c28ab6fe4b0efa6ebda1830/t/0c229aa71352374ab600b95cc5d2d8bc/p/assets/videos/2018/10/16/5bc57c56e4b0253afa0cb950/k/timestamp

You must debug regular player to know what you need to server return valid AES key.

**Comment by dexter101010** [comment]
> COOKIE as you know or not is send via HTTP header using option -h like that:
> -h "Cookie: NAME_1=VALUE_1; NAME_2=VALUE_2; NAME_3=VALUE_3;"
> 
> > credentials
> > ?
> 
> As I wrote you should debug what information are send to server when m3u8 is requested in regular player.
> 
> Same for AES key uri, you should check what server return when regular player request AES key.
> In your example AES key are downloaded using URL:
> https://cdn.spayee.in/spees/w/o/5b49b8f2e4b02ac9d5e71945/v/5bc57c56e4b0253afa0cb950/u/5c28ab6fe4b0efa6ebda1830/t/0c229aa71352374ab600b95cc5d2d8bc/p/assets/videos/2018/10/16/5bc57c56e4b0253afa0cb950/k/timestamp
> 
> You must debug regular player to know what you need to send to the server to got valid AES key.

Thank you sir for your answers. 

Here is a print screen with the command i did but still the same problem, Maybe the command does not pass the info to the hlsdl app ?

https://imgur.com/a/ouoPLOU

Thanks!

**Comment by e2iplayer** [comment]
Hi,

The User-Agent is set incorrectly, you should pass it like that:
-u "Mozilla....." 
not
-u "User-Agen: Mozilla..."

You need to set header name when you use option "-h". 
Anyway did you debug original player and how it download AES keys? 
Does AES keys downloaded by original player also change it time when requested from server?

**Comment by dexter101010** [comment]
It get  a key in encrypted form (48 bytes) but everytime i refresh the page with the video playing, the key it's changing (encrypted values). If you want and have time to play with it, i can give you the credentials of the site.

Hope still working because it's limited to 5 devices.
 
Thanks!

**Comment by dexter101010** [comment]
Hello sir, 

I wanna ask you something about the app : 

can we specify to the app on which segment will start first ?

Let's say the m3u8 have 500 segments (TS) and i want that the app start downloading with segment 2 instead of 1. Can it be possible ?

I am asking that because i saw something interesting on the encrypted m3u8 that i am having problem with download. Every m3u8 from that site, start with 00 segment : 

#EXTINF:2.400000,
hls_350k_000.ts
#EXTINF:2.400000,
hls_350k_001.ts
#EXTINF:1.200000,
hls_350k_002.ts
#EXTINF:2.400000,
hls_350k_003.ts
#EXTINF:2.400000,

But when the video play, the key request start after the 000 segment. So i think here is the problem with decrypting. Probably 000 segment is it there just to offer a wrong key when you are trying to downloading. That's why i am saying if there is possible to start with a specified segment and not with the first.

Thanks!

**Comment by e2iplayer** [comment]
No we can not. But I do not think that this is the problem.
As I wrote, you should first debug original player to know what AES key it use.

**Comment by dexter101010** [comment]
Thanks for your help!
